version: "3.9"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: gresau/localstack-persist:3
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"   
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/persisted-data"
      - "/var/run/docker.sock:/var/run/docker.sock"
